In [9]:
import numpy as np
import pandas as pd
from scipy.stats import norm
import scipy.optimize as opti
from scipy.optimize import LinearConstraint, Bounds
import wrds
import datetime
import statsmodels.api as sm
import matplotlib.pyplot as plt

# Exercise 2

In [2]:
db = wrds.Connection()
#antb95
#goqhuB-1hafqe-dojvix

Enter your WRDS username [bedanian]:antb95
Enter your password:········
WRDS recommends setting up a .pgpass file.
You can find more info here:
https://www.postgresql.org/docs/9.5/static/libpq-pgpass.html.
Loading library list...
Done


In [3]:
#import data
names = db.get_table(library='crsp', table='stocknames')
names =names.loc[:,['permco' , 'ticker']]
Ticker = 'MSFT'
inter = names['permco'].where(names['ticker'] == Ticker)
inter.dropna(inplace = True)
Permco = inter.iloc[0]
df = db.raw_sql("select prc, date from crsp.dsf where permco in ("+str(Permco)+") and date >='2011-04-07' and date <='2016-04-07'")
df.columns = ['MSFT' , 'Date']
df.set_index('Date',inplace = True)

In [4]:
df2 = pd.DataFrame()
df2 = (np.log(df) - np.log(df).shift(1))
df2.dropna(inplace = True)
df2.columns = ['R']
df2['Z'] = np.random.normal(0,1,len(df2))
df2.reset_index(inplace = True)

In [5]:
def sigma_t(alpha,x,t,sigma_0):
    if t == 0:
        return sigma_0
    else:
        return np.sqrt(alpha[0]+alpha[1]*x[t-1]**2+alpha[2]*sigma_t(alpha,x,t-1,sigma_0)**2)

In [6]:
def L(alpha,x,sigma_0):
    l = 0
    for k in range(len(x)):
        sigma = sigma_t(alpha,x,k,sigma_0)
        l *= norm.pdf(x[k]/sigma)/sigma
    return l

In [10]:
index_0 = df2[df2['Date'] == datetime.date(2013,4,8)].index.values[0]
i = 0 
x0 = [(0.2**2)/(1-0.1-0.8),0.1,0.8]
bnds = Bounds([10**(-8),0,0], [np.inf,np.inf,np.inf], keep_feasible=True)
x = list(df2['R'])
while i+index_0 < len(x):  
    xi = x[i:index_0+i]
    mu = np.mean(xi)
    xi = xi - mu
    sigma_0 = np.std(xi)
    fun = lambda alpha: -L(alpha,xi,sigma_0)
    print(opti.minimize(fun, x0, method='SLSQP', bounds = bnds).x)
    i=i+1
    if i > 20:
        break  

[0.4 0.1 0.8]
[0.4 0.1 0.8]
[0.4 0.1 0.8]
[0.4 0.1 0.8]
[0.4 0.1 0.8]
[0.4 0.1 0.8]
[0.4 0.1 0.8]
[0.4 0.1 0.8]
[0.4 0.1 0.8]
[0.4 0.1 0.8]
[0.4 0.1 0.8]
[0.4 0.1 0.8]
[0.4 0.1 0.8]
[0.4 0.1 0.8]
[0.4 0.1 0.8]
[0.4 0.1 0.8]
[0.4 0.1 0.8]
[0.4 0.1 0.8]
[0.4 0.1 0.8]
[0.4 0.1 0.8]
[0.4 0.1 0.8]


In [11]:
df2

Date         R         Z
0     2011-04-08 -0.004974  0.413620
1     2011-04-11 -0.003458 -0.032286
2     2011-04-12 -0.013173 -1.128588
3     2011-04-13 -0.000390 -1.152169
4     2011-04-14 -0.008227 -1.353410
5     2011-04-15 -0.001969 -0.296673
6     2011-04-18 -0.011497  1.407170
7     2011-04-19  0.002787 -0.182258
8     2011-04-20  0.023965 -0.888440
9     2011-04-21 -0.009360 -0.164777
10    2011-04-25  0.003520 -2.794957
11    2011-04-26  0.022395  0.175765
12    2011-04-27  0.007228 -1.802081
13    2011-04-28  0.012432 -0.769386
14    2011-04-29 -0.030023 -0.650907
15    2011-05-02 -0.010082  0.307710
16    2011-05-03  0.005829 -0.177916
17    2011-05-04  0.009640  0.388363
18    2011-05-05 -0.010415 -0.560121
19    2011-05-06  0.003097  1.213023
20    2011-05-09 -0.001547  0.343301
21    2011-05-10 -0.006214  0.172291
22    2011-05-11 -0.012150  0.311060
23    2011-05-12 -0.001579 -0.484254
24    2011-05-13 -0.011519  0.929936
25    2011-05-16 -0.018549  1.580725
26    2011-05-17 -0.002037  0.940605
27    2011-05-18  0.006909 -1.374828
28    2011-05-19  0.001012  1.010271
29    2011-05-20 -0.009145 -0.774920
...          ...       ...       ...
1227  2016-02-25  0.014305  1.033830
1228  2016-02-26 -0.015474 -1.793908
1229  2016-02-29 -0.008221  0.424162
1230  2016-03-01  0.032866  1.649625
1231  2016-03-02  0.007012  1.102998
1232  2016-03-03 -0.011396 -0.323446
1233  2016-03-04 -0.006131  0.882660
1234  2016-03-07 -0.019407  0.010838
1235  2016-03-08  0.012077 -0.674606
1236  2016-03-09  0.022778 -0.040851
1237  2016-03-10 -0.015064 -0.125794
1238  2016-03-11  0.019407  1.062530
1239  2016-03-14  0.001883 -0.284530
1240  2016-03-15  0.007868  0.129643
1241  2016-03-16  0.014082 -0.391944
1242  2016-03-17  0.005688  1.105081
1243  2016-03-18 -0.021637 -0.070199
1244  2016-03-21  0.006893  0.942590
1245  2016-03-22  0.003891 -0.091905
1246  2016-03-23 -0.001851 -0.232930
1247  2016-03-24  0.004437  1.319790
1248  2016-03-28 -0.012436 -0.565462
1249  2016-03-29  0.021617  0.389444
1250  2016-03-30  0.006195 -0.275587
1251  2016-03-31  0.003264 -0.703592
1252  2016-04-01  0.006137 -1.423823
1253  2016-04-04 -0.002523 -0.051059
1254  2016-04-05 -0.015820 -0.012354
1255  2016-04-06  0.010212 -0.006377
1256  2016-04-07 -0.012046 -0.375217

[1257 rows x 3 columns]